// Description: This procedure is called during command line renders
// with the Render executable.
//
global proc hydraStormCmdRender(string $option)
{
    hydraRender -renderer HdStormRendererPlugin;
}

// Description: This procedure is called during batch rendering launched
// interactively from Maya.
global proc hydraStormBatchRender(string $option)
{
    hydraRender -renderer HdStormRendererPlugin;
}

// Description: render with HdStormRendererPlugin, the Hydra Storm renderer.
//
global proc hydraStormRender(int $width, int $height, int $doShadows,
        int $doGlowPass, string $camera, string $option)
{
    hydraRender -renderer HdStormRendererPlugin;
}

// Description: This script returns the Hydra-specific command line arguments
// to the 'Render' executable on batch render from interactive mode.
//
global proc string hydraStormBatchRenderOptionsString()
{
	return " -r hydraStorm ";
}
