//
// Copyright 2026 Autodesk, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

global proc mayaHydraSetRenderWidth(int $width)
{
    python("import mayaHydra.renderSettings.resolution as mhResolution; mhResolution.setWidth(" + $width + ")");
}

global proc mayaHydraSetRenderHeight(int $height)
{
    python("import mayaHydra.renderSettings.resolution as mhResolution; mhResolution.setHeight(" + $height + ")");
}

global proc mayaHydraSetRenderDirectory(string $rd)
{
    // Use Python raw string to support Windows path backslashes.
    python("import mayaHydra.renderSettings.output as mhOutput; mhOutput.setRenderDirectory(" + "r\"" + $rd + "\")");
}

global proc mayaHydraSetRenderImageName(string $im)
{
    python("import mayaHydra.renderSettings.output as mhOutput; mhOutput.setImageName(" + "\"" + $im + "\")");
}

global proc mayaHydraSetRenderOutputFormat(string $of)
{
    python("import mayaHydra.renderSettings.output as mhOutput; mhOutput.setOutputFormat(" + "\"" + $of + "\")");
}
