// Description: This procedure is called to register Hydra Arnold as a
// renderer.
//
// *** WARNING ***  Experimental code, not for production.  There should be
// a simple way of registering all Hydra renderers, not just a single one.
//

global proc registerHydraArnoldRenderer()
{
    renderer
        -rendererUIName                 "Hydra Arnold"
        -commandRenderProcedure         "hydraArnoldCmdRender"
        -batchRenderProcedure           "hydraArnoldBatchRender"
        -renderProcedure                "hydraArnoldRender"
        -renderDiagnosticsProcedure     ""
        -renderRegionProcedure          ""
        -iprRenderProcedure             ""
        -iprOptionsProcedure            ""
        -startIprRenderProcedure        ""
        -stopIprRenderProcedure         ""
        -changeIprRegionProcedure       ""
        -iprOptionsMenuLabel            ""
        -iprOptionsSubMenuProcedure     ""
        -iprRenderSubMenuProcedure      ""
        -batchRenderOptionsProcedure    ""
        -batchRenderOptionsStringProcedure "hydraArnoldBatchRenderOptionsString"
        -cancelBatchRenderProcedure     "batchRender"
        -showBatchRenderProcedure       "batchRender -showImage true"
        -showRenderLogProcedure         ""
        -showBatchRenderLogProcedure    ""
        -renderSequenceProcedure        "mayaRenderSequence"
        -textureBakingProcedure         ""
        -polyPrelightProcedure          ""
        -renderingEditorsSubMenuProcedure ""
        -supportColorManagement         true
        hydraArnold;

    // The first argument of the "-addGlobalsTab" flag is used in
    // creating layout names and should not be localized.

    renderer -edit
        -addGlobalsTab               "Common"
                                     "createMayaSoftwareCommonGlobalsTab"
                                     "updateMayaSoftwareCommonGlobalsTab"
        hydraArnold;
    renderer -edit
        -addGlobalsTab               "Hydra Arnold"
                                     "createHydraArnoldGlobalsTab"
                                     "updateHydraArnoldGlobalsTab"
        hydraArnold;

    // Unsure about what to do here, a Hydra-based renderer may not have
    // a Maya render globals node.  PPT, 21-Feb-2025.
    // renderer -edit -addGlobalsNode "hardwareRenderingGlobals" hydraArnold;
    renderer -edit -addGlobalsNode "defaultRenderGlobals" hydraArnold;
    renderer -edit -addGlobalsNode "defaultResolution" hydraArnold;
}
