// Copyright 2024 Autodesk
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

global proc mayaHydra_registerUI_load()
// Callback registered with the MFnPlugin for when the plugin is loaded.
// Used to initialize any UI we create.
{
    print("PPT: in mayaHydra_registerUI_load()\n"); 

    source "mayaHydra_GeomSubsetsPickMode.mel";
    mayaHydra_GeomSubsetsPickMode_SetupUI();

    source "mayaHydra_create_globals_tab_Storm.mel";
    // FIXME Arnold Hydra renderer render settings UI tab should NOT
    // be done here.
    source "mayaHydra_create_globals_tab_Arnold.mel";
}
