// Description: This procedure is called during command line renders
// with the Render executable.
//
global proc hydraStormCmdRender(string $option)
{
    // No interactive Maya to provide an OpenGL context, so ask for one.
    hydraRender -renderer HdStormRendererPlugin -gpu 1;
}

// Description: This procedure is called during batch rendering launched
// interactively from Maya.
global proc hydraStormBatchRender(string $option)
{
    // No interactive Maya to provide an OpenGL context, so ask for one.
    hydraRender -renderer HdStormRendererPlugin -gpu 1;
}

// Description: This procedure is called for render current frame launched
// interactively from Maya.
//
global proc hydraStormRender(int $width, int $height, int $doShadows,
        int $doGlowPass, string $camera, string $option)
{
    // Interactive Maya provides the OpenGL context, no need to ask for one.
    hydraRender -renderer HdStormRendererPlugin;
}

// Description: This script returns the Hydra-specific command line arguments
// to the 'Render' executable on batch render from interactive mode.
//
global proc string hydraStormBatchRenderOptionsString()
{
	return " -r hydraStorm ";
}
