// Description: This procedure is called during command line renders
// with the Render executable.
//
global proc hydraArnoldCmdRender(string $option)
{
    hydraRender -renderer HdArnoldRendererPlugin;
}

// Description: This procedure is called during batch rendering launched
// interactively from Maya.
global proc hydraArnoldBatchRender(string $option)
{
    hydraRender -renderer HdArnoldRendererPlugin;
}

// Description: render with HdArnoldRendererPlugin, the Hydra Arnold renderer.
//
global proc hydraArnoldRender(int $width, int $height, int $doShadows,
        int $doGlowPass, string $camera, string $option)
{
    hydraRender -renderer HdArnoldRendererPlugin;
}

// Description: This script returns the Hydra-specific command line arguments
// to the 'Render' executable on batch render from interactive mode.
//
global proc string hydraArnoldBatchRenderOptionsString()
{
	return " -r hydraArnold ";
}
