//==================================================================
// Hydra Prman Renderer Tab
//==================================================================

// Copy-pasted and adapted from createMayaHardware2GlobalsTab.mel

// Description: Utility procedure used by other procedures in this file.
//              Must be used to account for multiple instances of the same tab.
//
global proc setParentToPrmanTab()
{
	// First set the parent to the correct tab layout.
	// Account for the special "all renderers" master layer layout
	// when we are using render layers
	global string $gMasterLayerRendererName;
	string $renderer = isDisplayingAllRendererTabs() ? $gMasterLayerRendererName : `currentRenderer`;
	string $tabLayout = rendererTabLayoutName($renderer);
	setParent $tabLayout;

	// Now set the parent to the correct column layout
	setParent hardware2TabColumn;
}

// To be filled in later.
global proc updateAnPrmanSetting()
{
	string $oldParent = `setParent -query`;
	setParentToPrmanTab();

	// Pass

	setParent $oldParent;
}

// Description:
// This procedure is called to create the "Hydra Prman" globals tab
// in the unified render globals for the Hydra Prman renderer.
global proc createHydraPrmanGlobalsTab()
{
    global string $gBatchRenderOverrideMenu;

	string $parentForm = `setParent -query`;

	scrollLayout -horizontalScrollBarThickness 0 -childResizable true scrollLayout;
		columnLayout -adjustableColumn true hardware2TabColumn;

			setUITemplate -pushTemplate attributeEditorTemplate;

					// Create the UI for a setting.
					frameLayout -label "A Setting" -collapsable true -collapse false aSettingOptions;
						columnLayout -adjustableColumn true;
							text "The Setting";
						setParent ..;
					setParent ..;

			setUITemplate -popTemplate;

		setParent ..;
    setParent ..;

	formLayout
		-edit
		-af scrollLayout "top" 0
		-af scrollLayout "bottom" 0
		-af scrollLayout "left" 0
		-af scrollLayout "right" 0
		$parentForm;

	updateHydraPrmanGlobalsTab();
}

global proc updateHydraPrmanGlobalsTab()
{
	updateAnPrmanSetting();
}
