// Description: This procedure is called to register Hydra Prman as a
// renderer.
//
// *** WARNING ***  Experimental code, not for production.  There should be
// a simple way of registering all Hydra renderers, not just a single one.
//

global proc registerHydraPrmanRenderer()
{
    renderer
        -rendererUIName                 "Hydra Prman"
        -commandRenderProcedure         "hydraPrmanCmdRender"
        -batchRenderProcedure           "hydraPrmanBatchRender"
        -renderProcedure                "hydraPrmanRender"
        -renderDiagnosticsProcedure     ""
        -renderRegionProcedure          ""
        -iprRenderProcedure             ""
        -iprOptionsProcedure            ""
        -startIprRenderProcedure        ""
        -stopIprRenderProcedure         ""
        -changeIprRegionProcedure       ""
        -iprOptionsMenuLabel            ""
        -iprOptionsSubMenuProcedure     ""
        -iprRenderSubMenuProcedure      ""
        -batchRenderOptionsProcedure    ""
        -batchRenderOptionsStringProcedure "hydraPrmanBatchRenderOptionsString"
        -cancelBatchRenderProcedure     "batchRender"
        -showBatchRenderProcedure       "batchRender -showImage true"
        -showRenderLogProcedure         ""
        -showBatchRenderLogProcedure    ""
        -renderSequenceProcedure        "mayaRenderSequence"
        -textureBakingProcedure         ""
        -polyPrelightProcedure          ""
        -renderingEditorsSubMenuProcedure ""
        -supportColorManagement         true
        hydraPrman;

    // The first argument of the "-addGlobalsTab" flag is used in
    // creating layout names and should not be localized.

    renderer -edit
        -addGlobalsTab               "Common"
                                     "createMayaSoftwareCommonGlobalsTab"
                                     "updateMayaSoftwareCommonGlobalsTab"
        hydraPrman;
    renderer -edit
        -addGlobalsTab               "Hydra Prman"
                                     "createHydraPrmanGlobalsTab"
                                     "updateHydraPrmanGlobalsTab"
        hydraPrman;

    // Unsure about what to do here, a Hydra-based renderer may not have
    // a Maya render globals node.  PPT, 21-Feb-2025.
    // renderer -edit -addGlobalsNode "hardwareRenderingGlobals" hydraPrman;
    renderer -edit -addGlobalsNode "defaultRenderGlobals" hydraPrman;
    renderer -edit -addGlobalsNode "defaultResolution" hydraPrman;
}
