// Description: This procedure is called to register Hydra Storm as a
// renderer.
//
// *** WARNING ***  Experimental code, not for production.  There should be
// a simple way of registering all Hydra renderers (e.g. Hydra
// Arnold), not just Hydra Storm.
//

global proc registerHydraStormRenderer()
{
    renderer
        -rendererUIName                 "Hydra Storm"
        -commandRenderProcedure         "hydraStormCmdRender"
        -batchRenderProcedure           "hydraStormBatchRender"
        -renderProcedure                "hydraStormRender"
        -renderDiagnosticsProcedure     ""
        -renderRegionProcedure          ""
        -iprRenderProcedure             ""
        -iprOptionsProcedure            ""
        -startIprRenderProcedure        ""
        -stopIprRenderProcedure         ""
        -changeIprRegionProcedure       ""
        -iprOptionsMenuLabel            ""
        -iprOptionsSubMenuProcedure     ""
        -iprRenderSubMenuProcedure      ""
        -batchRenderOptionsProcedure    ""
        -batchRenderOptionsStringProcedure "hydraStormBatchRenderOptionsString"
        -cancelBatchRenderProcedure     "batchRender"
        -showBatchRenderProcedure       "batchRender -showImage true"
        -showRenderLogProcedure         ""
        -showBatchRenderLogProcedure    ""
        -renderSequenceProcedure        "mayaRenderSequence"
        -textureBakingProcedure         ""
        -polyPrelightProcedure          ""
        -renderingEditorsSubMenuProcedure ""
        -supportColorManagement         true
        hydraStorm;

    // The first argument of the "-addGlobalsTab" flag is used in
    // creating layout names and should not be localized.

    renderer -edit
        -addGlobalsTab               "Common"
                                     "createMayaSoftwareCommonGlobalsTab"
                                     "updateMayaSoftwareCommonGlobalsTab"
        hydraStorm;
    renderer -edit
        -addGlobalsTab               "Hydra Storm"
                                     "createHydraStormGlobalsTab"
                                     "updateHydraStormGlobalsTab"
        hydraStorm;

    // Unsure about what to do here, a Hydra-based renderer may not have
    // a Maya render globals node.  PPT, 21-Feb-2025.
    // renderer -edit -addGlobalsNode "hardwareRenderingGlobals" hydraStorm;
    renderer -edit -addGlobalsNode "defaultRenderGlobals" hydraStorm;
    renderer -edit -addGlobalsNode "defaultResolution" hydraStorm;
}
